version: 2
registries:
  maven-repository-nexus-adaptris-net-nexus-content-groups-interlo:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: agility
    password: "${{secrets.MAVEN_REPOSITORY_NEXUS_ADAPTRIS_NET_NEXUS_CONTENT_GROUPS_INTERLO_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  registries:
  - maven-repository-nexus-adaptris-net-nexus-content-groups-interlo
